[tool.poetry]
name = "docdeid"
version = "0.0.12"
description = "Under construction."
authors = ["Vincent Menger <vmenger@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pylint = "^2.12.1"
isort = "^5.10.1"
pyment = "^0.3.3"
pytest-cov = "^3.0.0"
flake8-annotations = "^2.9.1"
black = "^22.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
