[tool.poetry]
name = "arbache-authentication"
version = "1.0.5"
description = "Pacote de autenticações das aplicações Arbache"
authors = ["Willames <williames@arbache.com>"]

[tool.poetry.dependencies]
python = "^3.10.4"
Django = "^4.0.0"
djangorestframework = "^3.13.1"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pre-commit = "^2.19.0"
twine = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
