[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "investec_open_api"
version = "0.0.1"
authors = [
  { name="Devin Pearson", email="devin@blackhat.co.za" },
]
description = "A connector for the Investec Open API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/devinpearson/investec_open_api"
"Bug Tracker" = "https://github.com/devinpearson/investec_open_api/issues"
