[tool.poetry]
name = "rafal-test23"
version = "0.8.0"
description = ""
authors = ["Rafa≈Ç Majewski <goodheropl@gmail.com>"]
packages = [
	{ include = "rafaltest", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
tox = "^3.26.0"
flake8 = "^5.0.4"
pylint = "^2.15.3"
mypy = "^0.982"
yapf = "^0.32.0"
toml = "^0.10.2"
pylint-quotes = "^0.2.3"
black = "^22.10.0"
poethepoet = "^0.16.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
formatting-fix = { shell = "black src && yapf -i -r src" }
formatting-check = { shell = "pylint --load-plugins=pylint_quotes --disable=all --enable=invalid-string-quote src" }
linting-check = { shell = "pylint --load-plugins=pylint_quotes --disable=FORMAT,invalid-string-quote src" }
typing-check = { shell = "mypy src" }
