[tool.poetry]
name = "tv-audio-extractor"
version = "0.1.2"
description = "Extracts audio from tv shows and tags them appropriately"
authors = ["David Padbury <david@davidpadbury.com>"]

[tool.poetry.dependencies]
python = "^3.9"
parse-torrent-title = "^2.4"
typer = "^0.6.1"
rich = "^12.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tv-audio-extractor = 'tv_audio_extractor.main:main'