[tool.poetry]
name = "ears"
version = "0.1.1"
description = ""
authors = ["FÃ©lix Voituret <fvoituret@deezer.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.23.0"
google-cloud-pubsub = "^2.13.7"
pydantic = "^1.10.2"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]
mypy = "^0.981"
isort = "^5.10.1"
black = "^22.8.0"
pytest = "^7.1.3"
pytest-mock = "^3.9.0"
pytest-httpx = "^0.21.0"
slackette = "^0.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3