[tool.poetry]
name = "pycryptaes"
version = "0.1.4"
description = "Encrypt and Decrypt Data via AES encryption - a pycryptodome python package wrapper"
authors = ["Gwang Jin Kim <gwang.jin.kim.phd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pycryptodome = "^3.15.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
