[tool.poetry]
name = "mdatpy"
version = "0.0.4rc"
description = "A pypi release of the MDAT"
authors = ["Abhijeet Parida <abhijeet.parida@tum.de>"]
license = "MIT"
repository = 'https://github.com/a-parida12/MDAT'
readme = 'README.md'
keywords = []

[tool.poetry.dependencies]
python = "~3.10.0"
tensorflow = "^2.10.0"
tensorflow-gpu = "^2.10.0"
scikit-image = "^0.19.3"
networkx = "^2.8.7"
itk = "5.3rc4"
matplotlib = "^3.6.0"
tqdm = "^4.64.1"
nekton = "0.2.6rc2"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"
bandit = "^1.7.1"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
