[tool.isort]
profile = "black"
order_by_type = true

[tool.poetry]
name = "free-ssl-proxies"
version = "0.1.1"
description = "A minimal python library that scrapes ssl proxies from https://sslproxies.org."
authors = ["Jamin Becker"]

readme = "README.md"
requires-python = ">=3.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/JaminB/free-ssl-proxies"