[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FlightStream"
version = "0.0.801"
authors = [
  { name="Ligasy", email="author@example.com" },
]
description = "Integrate StreamDeck with Microsoft Flight Simulator"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Pillow>=9.0.0",
    "SimConnect>=0.4.23",
    "streamdeck>=0.9.0",
]
[project.urls]
"Homepage" = "https://github.com/pypa/flightstream"
"Bug Tracker" = "https://github.com/pypa/flightstream/issues"